// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1mfqRRVPiq4znBxmAT8Dw4WF1Kx78WnA',
    appId: '1:62851779558:web:2be9abd50f8fed7c05a427',
    messagingSenderId: '62851779558',
    projectId: 'munacha-9f0a2',
    authDomain: 'munacha-9f0a2.firebaseapp.com',
    storageBucket: 'munacha-9f0a2.appspot.com',
    measurementId: 'G-F7E8N7Y2CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMxzoMpFNPW8KMj-3gss7-UbKu73Q8Mj8',
    appId: '1:62851779558:android:54ca7353566b982105a427',
    messagingSenderId: '62851779558',
    projectId: 'munacha-9f0a2',
    storageBucket: 'munacha-9f0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJECpFrlP8i1WrPUpBS1C0jMyPu8uzyok',
    appId: '1:62851779558:ios:2a42aa49969dfd9905a427',
    messagingSenderId: '62851779558',
    projectId: 'munacha-9f0a2',
    storageBucket: 'munacha-9f0a2.appspot.com',
    iosBundleId: 'com.example.munachaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJECpFrlP8i1WrPUpBS1C0jMyPu8uzyok',
    appId: '1:62851779558:ios:2a42aa49969dfd9905a427',
    messagingSenderId: '62851779558',
    projectId: 'munacha-9f0a2',
    storageBucket: 'munacha-9f0a2.appspot.com',
    iosBundleId: 'com.example.munachaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1mfqRRVPiq4znBxmAT8Dw4WF1Kx78WnA',
    appId: '1:62851779558:web:cbb337cfeed2db4205a427',
    messagingSenderId: '62851779558',
    projectId: 'munacha-9f0a2',
    authDomain: 'munacha-9f0a2.firebaseapp.com',
    storageBucket: 'munacha-9f0a2.appspot.com',
    measurementId: 'G-9DTYC81VK2',
  );
}
